init_files_path: "initFiles/"
model_file: "model.h5"
checkpoint_file: "fl_checkpoint"
agg_checkpoint_file_path: "/fl_agg_checkpoint"
agg_checkpoint_weight_path: "/fl_agg_checkpoint_weight"
estimated_waiting_time: 20000
checkin_limit: 2
port: "50050"
fl_root_path: "./../data/"