INIT_FILES_PATH: "initFiles/"
MODEL_FILE: "model.h5"
CHECKPOINT_FILE: "fl_checkpoint"
AGG_CHECKPOINT_FILE_PATH: "/fl_agg_checkpoint"
AGG_CHECKPOINT_WEIGHT_PATH: "/fl_agg_checkpoint_weight"
ESTIMATED_WAITING_TIME: 20000
CHECKIN_LIMIT: 2
SELECTOR_ADDRESS: "localhost:50051"
WEBSERVER_ADDRESS: "localhost: 50052"
PORT: "50050"
FL_ROOT_PATH: "/data"
PROBLEM_ID: "DEFAULT"